M48
; DRILL file {KiCad 9.0.0} date 2026-03-06T00:50:46+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-06T00:50:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X138.85Y-105.15
X138.95Y-69.5
X197.5Y-105.1
X197.7Y-69.55
M30
